name: 'Publish Conda'
description: 'Build and Publish Conda package to Anaconda'
author: 'Ziyi Xi'
branding:
  icon: 'package'  
  color: 'purple'
inputs: 
  subdir:
    description: 'Sub-directory with conda recipe'
    default: '.'
  anacondatoken:
    description: 'Anaconda access token'
  platforms:
    description: 'Platforms to publish [osx/linux/win]'
    default: 'ubuntu-latest'
runs:
  using: 'docker'
  image: 'Dockerfile'
